### ISSUE TITLE
BOM坐标

### ISSUE THREAD

**Issue by Archmageone** [winking324/IntelliKnobClient#1]
请问BOM坐标文件是怎么生成的？直接从KICAD中导出吗

**Comment by winking324** [comment]
对，我是从 KiCAD 里面导出来的，可以参考：

[ViewBase v0.4 坐标](https://github.com/winking324/IntelliKnobClient/files/9336112/1659170394919.xlsx)

[ViewScreen v0.2 坐标](https://github.com/winking324/IntelliKnobClient/files/9336124/1659325610679.csv)
