### ISSUE TITLE
BOM表有吗

### ISSUE THREAD

**Issue by heibaidianying** [winking324/IntelliKnobClient#3]
kicad就不想装了，AD打不开，求一个BOM表

**Comment by winking324** [comment]
[ViewBase V0.4](https://github.com/winking324/IntelliKnob/files/9378586/ViewBase.zip)

[ViewScreen V0.2](https://github.com/winking324/IntelliKnob/files/9378585/ViewScreen.zip)

参考上面相关文件，**注意：** BOM 里面有些是标注信息（例如说螺丝信息等跟贴片无关的），你可以把这些信息删掉，不然贴片那边会问你这是那些元器件。
