### ISSUE TITLE
请问嘉立创有很多元件没有怎么办

### ISSUE THREAD

**Issue by yelfen** [winking324/IntelliKnobClient#4]

**Comment by winking324** [comment]
有很多都是可以用相同参数的零件替换的，剩下应该有几个没有的，你就需要自己从淘宝买了寄过去就可以了。

淘宝买的时候直接跟卖家说下，从嘉立创那边复制编号，让卖家写个纸头备注下，寄到嘉立创对应地址就可以了。

**Comment by winking324** [comment]
我邮寄的有下面这几个，你可以参考下，其他的应该在嘉立创都能找到。
![image](https://user-images.githubusercontent.com/7922054/192503161-1214758e-4ce2-4911-8d7b-10ba40596e25.png)
